import type { Metadata } from "next";
import StyledComponentsRegistry from "@/app/regisrty";
import Footer from "@/components/Footer";
import {playfairDisplay, raleway} from "@/fonts";
import Header from "@/components/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="ru" className={`${raleway.variable} ${playfairDisplay.variable}`}>
      <body>
      <StyledComponentsRegistry>
          <Header/>
          <main>{children}</main>
          <Footer/>
      </StyledComponentsRegistry>
      </body>
      </html>
  );
}
