import type { Metadata } from "next";
import "./globals.css";
import {Playfair_Display, Raleway} from "next/font/google";
import StyledComponentsRegistry from "@/app/regisrty";
import crossIcon from '@/app/assets/icons/cross.svg'
import Image from "next/image";
import {Header} from "@/app/styles";
import logo from '@/app/assets/logo.png'
import cartIcon from '@/app/assets/icons/cart.svg'
import favouritesIcon from '@/app/assets/icons/favourites.svg'

const raleway = Raleway({ subsets: ["cyrillic", "latin"], weight: ['200', '400', '700'], style: ['normal', 'italic'], variable: '--font-raleway'});
const playfairDisplay = Playfair_Display({ subsets: ["cyrillic", "latin"], weight: ['400', '600', '700'], style: ['normal', 'italic'], variable: '--font-playfair-display', });

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={`${raleway.variable} ${playfairDisplay.variable}`}>
      <body>
      <StyledComponentsRegistry>
          <Header>
              <div>
                  <div className={'container'}>
                      <h1>Получите скидку 15% по промокоду <u>MSDESIGN</u></h1>
                      <button><Image src={crossIcon} alt={'cross icon'} width={10} height={10}/></button>
                  </div>
              </div>
              <nav>
                  <div className="container">
                      <button><Image src={logo} alt={'MS Design logo'}/></button>
                      <ul>
                          <li><a href="#">Главная</a></li>
                          <li><a href="#">Каталог</a></li>
                          <li><a href="#">Контакты</a></li>
                      </ul>
                      <button><Image src={cartIcon} alt={'cart'}></Image></button>
                      <button><Image src={favouritesIcon} alt={'favourites'}></Image></button>
                  </div>
              </nav>
          </Header>
          <main>{children}</main>
          <footer></footer>
      </StyledComponentsRegistry>
      </body>
      </html>
  );
}
